//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet4.Model.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Capteur
    {
        public int ID_Cap { get; set; }
        public string Name { get; set; }
    }
}
