//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataReporting.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class releve
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public releve()
        {
            this.ligneReleve = new HashSet<ligneReleve>();
        }
    
        public int idReleve { get; set; }
        public int capteurID { get; set; }
        public System.DateTime dateReleve { get; set; }
    
        public virtual capteur capteur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ligneReleve> ligneReleve { get; set; }
    }
}
