//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataReporting.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class releve
    {
        public int idReleve { get; set; }
        public /*Nullable<DateTime>*/ DateTime dateReleve { get; set; }
        public /*Nullable<TimeSpan>*/ TimeSpan heureReleve { get; set; }
        public /*Nullable<double>*/ double temperature { get; set; }
        public /*Nullable<double>*/ double hygrometrie { get; set; }
        public /*Nullable<int>*/ int idCapteur { get; set; }
    
        public virtual capteur capteur { get; set; }
    }
}
